// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package core

import (
	"ImageGo/api/core"
)

type ControllerV1 struct{}

func NewV1() core.ICoreV1 {
	return &ControllerV1{}
}
